# The name of this automation "Robot"
name: SkyCheck CI/CD Pipeline

# This tells the robot: "Wake up whenever I push new code to the main branch"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # <--- Add this line! This creates the manual button

# These are the tasks the robot will perform
jobs:
  test-and-build:
    # GitHub will provide a free Linux computer for us to use
    runs-on: ubuntu-latest

    steps:
      # Step 1: Tell the Linux computer to download your code from GitHub
      - name: Get the code from GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Tell the Linux computer to try building your Docker image
      # This proves your Dockerfile actually works!
      - name: Test the Docker Build
        run: docker build -t skycheck-test .

      # Step 3: Run Sonar Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push-to-ecr:
  # We push the docker image to the image repo on AWS
    needs: test-and-build  # Only run this if the scan passes!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: skycheck-repository
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG